# -*- coding: utf-8 -*-
"""placement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b-2s84U80BlGzOC56amXZoRFUVzwaa4s
"""

import numpy as np
import pandas as pd

df=pd.read_csv("/placement.csv")

df.head()

df.shape



"""1 preprocess and eda and feature selection
2.extract input and output data
3 scale the values
4 train and test split
5 train the model
6 evaluate the model model selection
7 deploy the model

"""

#preprocessing
 df=df.iloc[:,1:]

df.head()

#eda
import matplotlib.pyplot as plt

plt.scatter(df["cgpa"],df["iq"],c=df["placement"])

#feature selection selection columns not used in this

x=df.iloc[:,0:2]
y=df.iloc[:,-1]

#train and test

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)

x_train

y_train

#scaling between 0 to 1
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

x_train=scaler.fit_transform(x_train)

x_train

x_test=scaler.transform(x_test)

x_test

from sklearn.linear_model import LogisticRegression

clf=LogisticRegression()

#modeltraining
clf.fit(x_train,y_train)

#evaluate
 #hidden data
 clf.predict(x_test)

y_pred=y_test

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

#plotting decision booundary
from mlxtend.plotting import plot_decision_regions
#import matplotlib.pyplot as plt

plot_decision_regions(x_train, y_train.values, clf=clf,  legend=2)

import pickle

pickle.dump(clf,open("model.pkl","wb"))

